### ISSUE TITLE
If I'm a Nebraska user, my dashboard displays summary rollup numbers with the appropriate Nebraska figures and data

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#578]
## ✨ What new feature do you want to see?
Nebraska users see summary stats that are different from the Illinois stats. These users see static data in those rollup figures.

## 🧶 Acceptance Criteria
- [x]  The rollup stats match those in the Nebraska mockup
- [x] The other header components match those in the NE mockup with static data (section currently says "Feb 2020 as of Feb 27) --> being addressed in #677 
- [x] I can see dynamic data for the As Of date #677 --> being addressed in #677 
- [x] I can see dynamic data for the Earned Revenue rollup number #715 
- [x] I can see dynamic data for the Estimated Revenue rollup number #716 
- [x] I can see dynamic data for the Max Revenue rollup number #717 
- [x] I can see dynamic data for Total Approved #720 
- [x] I can see dynamic data for the Transportation rollup number #718 
- [x]  The above criteria work in English and Spanish
- [x]  Verify accessibility (see details below)

## 🖍️ Implementation Details
Figma link: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=3579%3A1

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

## 🥧 Additional context
Figma mockup: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=3579%3A1
Spanish (see NE tab): https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=1049848154

**Comment by csprayregen** [comment]
Visual QA checklist:
- [ ]  Copy matches
- [ ]  Copy matches-ES
- [ ]  Sorting works on all columns
- [ ]  Colors
- [ ]  Font
- [ ]  Font size
- [ ]  Buttons (size, content)
- [ ]  Other interactions
- [ ]  Responsive
- [ ]  Icon (size, correct icon)
- [ ]  Padding
- [ ]  Spacing

**Comment by csprayregen** [comment]
Items to address:
- [ ] Missing the date fields at the top (see mockup and #677 referenced in QA)
